version: '3'

tasks:
  format:
    cmds:
    - deno fmt .
    - gofmt -w .
  generate:
    cmds:
    - go generate ./...
    - go build github.com/jtarchie/sqlite-chat
  lint: golangci-lint run --fix --timeout "10m"
  test: go run github.com/onsi/ginkgo/v2/ginkgo -cover -race -r
  default:
    cmds:
    - task: generate
    - task: format
    - task: lint
    - task: test